CREATE TABLE [dbo].[tbl_Users]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(MAX) NOT NULL, 
    [Surname] NVARCHAR(MAX) NOT NULL, 
    [Username] NVARCHAR(MAX) NOT NULL, 
    [DateOfBirth] DATE NOT NULL, 
    [Email] NVARCHAR(50) NOT NULL, 
    [PhonePrefix] NVARCHAR(5) NOT NULL,
    [Phone] NVARCHAR(50) NOT NULL, 
    [Adress] NVARCHAR(MAX) NOT NULL, 
    [City] NVARCHAR(MAX) NOT NULL, 
    [Country] NVARCHAR(MAX) NOT NULL, 
    [State] INT NOT NULL, 
    [ZipCode] NVARCHAR(50) NOT NULL, 
    [Role] INT NOT NULL, 
    [StripeID] NVARCHAR(MAX) NOT NULL, 
    [PasswordHash] VARBINARY(MAX) NOT NULL, 
    [PasswordSalt] VARBINARY(MAX) NOT NULL, 
    [EmailVerificationToken] NVARCHAR(MAX) NULL, 
    [EmailVerificationTokenExpires] DATETIME2 NULL, 
    [EmailVerifiedAt] DATETIME2 NULL, 
    [EmailVerified] BIT NULL DEFAULT 0,
    [SmsVerificationToken] INT NULL, 
    [SmsVerificationTokenExpires] DATETIME2 NULL, 
    [SmsVerifiedAt] DATETIME2 NULL,
    [SmsVerified] BIT NULL DEFAULT 0, 
    [PasswordResetToken] NVARCHAR(MAX) NULL, 
    [PasswordResetTokenExpires] DATETIME2 NULL, 
    [CreationDate] DATETIME2 NOT NULL DEFAULT GETDATE(), 
    [UserType] INT NOT NULL, 
    [CustomerCode] NVARCHAR(50) NULL
)
